[package]
name = "rust_bench"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
csv = "1.4.0"
kuva = { version = "0.2.0", features = ["cli", "png"] }
charton = { version = "0.5", features  = ["png", "parallel"]}
polars = { version = "0.53.0", features = ["lazy", "parquet"] }
plotters = "0.3"
time = { version = "0.3", features = ["formatting"] }
